inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tools/**/*'
    - 'test/rails/rails_root/**/*'
    - 'vendor/jpmobile-*/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/BlockDelimiters:
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
  Exclude:
    # For support original style
    - 'lib/jpmobile/resolver.rb'
    - 'lib/jpmobile/mail.rb'
  EnforcedStyle: braces_for_chaining

Style/IndentationConsistency:
  EnforcedStyle: normal

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/mobile/au.rb'
    - 'lib/jpmobile/mobile/docomo.rb'

Metrics/LineLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
